[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry]
name = "silnlp"
version = "1.0.0"
description = ""
authors = ["SIL International"]

[tool.poetry.dependencies]
python = ">=3.7"
pandas = "^1.0.4"
sentencepiece = "^0.1.95"
nltk = "^3.5"
python-dotenv = "^0.13.0"
seaborn = "^0.10.1"
morfessor = "^2.0.6"
Morfessor-FlatCat = "^1.0.8"
psutil = "^5.7.3"
scikit-learn = "^0.23.2"
numpy = "1.19.3"
OpenNMT-tf = "^2.16.0"
annoy = "^1.17.0"
lit-nlp = {url = "https://github.com/ddaspit/lit/releases/download/v0.2/lit_nlp-0.2-py3-none-any.whl"}
tensorflow = "^2.4.1"
google-cloud-translate = "^3.0.2"
clearml = {extras = ["s3"], version = ">=0.17.5"}
s3path = ">=0.2.203"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
flake8 = "^3.9.0"
