[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry]
name = "nlp_mt_testing"
version = "1.0.0"
description = ""
authors = ["SIL International"]

[tool.poetry.dependencies]
python = "~3.6.1"
opennmt-tf = "^2.12.0"
pandas = "^1.0.4"
sentencepiece = "^0.1.92"
scikit-learn = "^0.23.1"
nltk = "^3.5"
python-dotenv = "^0.13.0"
xmltodict = "^0.12.0"
seaborn = "^0.10.1"
lxml = "^4.5.1"
pandas-summary = "^0.0.7"
docopt = "^0.6.2"
morfessor = "^2.0.6"
Morfessor-FlatCat = "^1.0.8"
psutil = "^5.7.3"

[tool.poetry.dev-dependencies]
mypy = "^0.780"
black = "^19.10b0"
flake8 = "^3.8.3"
